[package]
name = "grpc-material"
version = "0.1.0"
authors = ["lynss <ly1169134156@163.com>"]
edition = "2018"

[dependencies]
protobuf = "2.4.0"
futures = "0.1.25"
grpc = "0.6.1"
futures-cpupool = "0.1.8"

[build-dependencies]
protoc-rust-grpc = "0.6.1"